"""Signal post-processing utilities."""

from .postprocess import (
    QuantileDropRule,
    SignalPostprocessResult,
    apply_quantile_drop,
    apply_signal_postprocess,
    load_table,
    write_postprocess_outputs,
)
from .simple_backtest import (
    SimpleBacktestConfig,
    SimpleBacktestResult,
    build_horizon_returns,
    build_rolling_sleeve_daily,
    compute_annual_metrics,
    compute_nonoverlap_cohort_metrics,
    compute_return_profile,
    compute_target_weight_turnover,
    compute_turnover_metrics,
    prepare_benchmark_forward_returns,
    prepare_benchmark_one_period_returns,
    prepare_forward_returns,
    prepare_one_period_returns,
    run_simple_signal_backtest,
    run_simple_signal_backtest_from_lab,
    select_signal,
    write_simple_backtest_outputs,
)

__all__ = [
    "QuantileDropRule",
    "SimpleBacktestConfig",
    "SimpleBacktestResult",
    "SignalPostprocessResult",
    "apply_quantile_drop",
    "apply_signal_postprocess",
    "build_horizon_returns",
    "build_rolling_sleeve_daily",
    "compute_annual_metrics",
    "compute_nonoverlap_cohort_metrics",
    "compute_return_profile",
    "compute_target_weight_turnover",
    "compute_turnover_metrics",
    "load_table",
    "prepare_benchmark_forward_returns",
    "prepare_benchmark_one_period_returns",
    "prepare_forward_returns",
    "prepare_one_period_returns",
    "run_simple_signal_backtest",
    "run_simple_signal_backtest_from_lab",
    "select_signal",
    "write_postprocess_outputs",
    "write_simple_backtest_outputs",
]
